<!-- Generated by GenStack (tool that converts AWS PartyRock apps to Svelte apps) -->

<div class="p-1 flex flex-row justify-end">
  <div class="bg-gray-300 text-black rounded p-2 ml-4">
    <slot />
  </div>
</div>