<!-- Generated by GenStack (tool that converts AWS PartyRock apps to Svelte apps) -->

<script lang="ts">
  export let base64Image: String;
</script>

<img src="data:image/png;base64,{base64Image}" alt="Generated by prompt" />